import type { Locale } from './i18n';

export interface GlossaryEntry {
  title: Record<Locale, string>;
  definition: Record<Locale, string>;
}

// Definitions intentionally start with the everyday meaning. Technical terms
// are included only to help readers understand the tutorials and library labels.
export const GLOSSARY: Record<string, GlossaryEntry> = {
  'ai-assistant': { title: { en: 'AI assistant', pl: 'Asystent AI' }, definition: { en: 'A service such as ChatGPT, Claude, or Gemini that understands written instructions and helps with tasks.', pl: 'Usługa taka jak ChatGPT, Claude lub Gemini, która rozumie polecenia i pomaga w zadaniach.' } },
  chat: { title: { en: 'Chat', pl: 'Czat' }, definition: { en: 'A conversation with an AI. The messages in it give the AI context for its next answer.', pl: 'Rozmowa z AI. Wiadomości w niej dają AI kontekst do kolejnej odpowiedzi.' } },
  model: { title: { en: 'AI model', pl: 'Model AI' }, definition: { en: 'The trained engine that produces an answer. Different models can be faster, more creative, or better at particular tasks.', pl: 'Wytrenowany silnik, który tworzy odpowiedź. Różne modele mogą być szybsze, bardziej kreatywne albo lepsze w konkretnych zadaniach.' } },
  prompt: { title: { en: 'Prompt', pl: 'Prompt' }, definition: { en: 'The question or instruction you give an AI. Clear details about the goal, audience, and format usually improve the result.', pl: 'Pytanie lub instrukcja dla AI. Jasny opis celu, odbiorcy i formatu zwykle poprawia wynik.' } },
  context: { title: { en: 'Context', pl: 'Kontekst' }, definition: { en: 'Information the AI can use to understand your request, such as earlier messages, a file, or project instructions.', pl: 'Informacje, z których AI może skorzystać, aby zrozumieć prośbę — wcześniejsze wiadomości, plik lub instrukcje projektu.' } },
  'file-upload': { title: { en: 'File upload', pl: 'Przesłanie pliku' }, definition: { en: 'Giving an AI a PDF, photo, spreadsheet, or another file to read or work with. Check what happens to sensitive files before uploading.', pl: 'Przekazanie AI PDF-a, zdjęcia, arkusza lub innego pliku do analizy. Przed przesłaniem sprawdź zasady dotyczące wrażliwych danych.' } },
  multimodal: { title: { en: 'Multimodal', pl: 'Wielomodalny' }, definition: { en: 'Able to work with more than one kind of input, for example text, images, audio, or files.', pl: 'Możliwość pracy z więcej niż jednym rodzajem danych, np. tekstem, obrazami, dźwiękiem lub plikami.' } },
  'web-search': { title: { en: 'Web search', pl: 'Wyszukiwanie w internecie' }, definition: { en: 'A feature that lets the AI look for current information online. Important claims should still be checked in the linked sources.', pl: 'Funkcja pozwalająca AI szukać aktualnych informacji online. Ważne twierdzenia nadal warto sprawdzić w podanych źródłach.' } },
  source: { title: { en: 'Source', pl: 'Źródło' }, definition: { en: 'The page, document, person, or data behind a claim. A good answer makes important sources easy to open and check.', pl: 'Strona, dokument, osoba lub dane, na których opiera się informacja. Dobra odpowiedź pozwala łatwo sprawdzić ważne źródła.' } },
  citation: { title: { en: 'Citation', pl: 'Cytowanie' }, definition: { en: 'A reference that shows where a statement came from, usually a link, title, and date.', pl: 'Wskazanie, skąd pochodzi informacja — zwykle link, tytuł i data.' } },
  'deep-research': { title: { en: 'Deep Research', pl: 'Deep Research' }, definition: { en: 'A longer research mode that gathers and compares multiple sources before preparing a report. It can take more time and still needs a human check.', pl: 'Tryb dłuższego researchu, który zbiera i porównuje wiele źródeł przed przygotowaniem raportu. Może trwać dłużej i nadal wymaga ludzkiej weryfikacji.' } },
  project: { title: { en: 'Project', pl: 'Projekt' }, definition: { en: 'A workspace that keeps related chats, files, and instructions together for one ongoing topic.', pl: 'Miejsce, które łączy rozmowy, pliki i instrukcje dotyczące jednego dłuższego tematu.' } },
  memory: { title: { en: 'Memory', pl: 'Pamięć' }, definition: { en: 'A setting that lets an AI remember selected preferences or facts between conversations. Do not store secrets there.', pl: 'Ustawienie pozwalające AI pamiętać wybrane preferencje lub fakty między rozmowami. Nie zapisuj tam sekretów.' } },
  'temporary-chat': { title: { en: 'Temporary chat', pl: 'Czat tymczasowy' }, definition: { en: 'A conversation designed not to use or add to your usual memory. Exact retention rules depend on the service.', pl: 'Rozmowa, która nie korzysta ze stałej pamięci i zwykle jej nie uzupełnia. Dokładne zasady przechowywania zależą od usługi.' } },
  'voice-mode': { title: { en: 'Voice mode', pl: 'Tryb głosowy' }, definition: { en: 'A way to talk with an AI using your microphone and hear its reply instead of typing.', pl: 'Sposób rozmowy z AI przez mikrofon i głośnik, bez konieczności pisania.' } },
  app: { title: { en: 'App', pl: 'Aplikacja' }, definition: { en: 'A program for a phone or computer, such as the ChatGPT, Claude, or Gemini app.', pl: 'Program na telefon lub komputer, np. aplikacja ChatGPT, Claude lub Gemini.' } },
  connector: { title: { en: 'Connector', pl: 'Połączenie (connector)' }, definition: { en: 'A controlled link between an AI and another service, such as Gmail, Google Drive, or Notion.', pl: 'Kontrolowane połączenie AI z inną usługą, np. Gmailem, Dyskiem Google lub Notion.' } },
  integration: { title: { en: 'Integration', pl: 'Integracja' }, definition: { en: 'A setup that makes two services work together, often with your permission and chosen access level.', pl: 'Konfiguracja, dzięki której dwie usługi współpracują, zwykle za twoją zgodą i z wybranym poziomem dostępu.' } },
  permission: { title: { en: 'Permission', pl: 'Uprawnienie' }, definition: { en: 'The access you grant an app or AI, such as reading files or sending email. Give only what is needed.', pl: 'Dostęp przyznany aplikacji lub AI, np. do czytania plików albo wysyłania e-maili. Przyznawaj tylko niezbędny zakres.' } },
  oauth: { title: { en: 'Sign-in permission (OAuth)', pl: 'Zgoda na logowanie (OAuth)' }, definition: { en: 'A safer sign-in flow where you approve access on the service’s own website without sharing your password with another app.', pl: 'Bezpieczniejszy sposób logowania: zatwierdzasz dostęp na stronie usługi, bez podawania hasła innej aplikacji.' } },
  imap: { title: { en: 'IMAP', pl: 'IMAP' }, definition: { en: 'A standard that lets an email app read and synchronize messages kept on an email provider’s server.', pl: 'Standard, dzięki któremu aplikacja pocztowa odczytuje i synchronizuje wiadomości przechowywane na serwerze dostawcy poczty.' } },
  'app-password': { title: { en: 'App password', pl: 'Hasło aplikacji' }, definition: { en: 'A separate, limited password made for one app or connection. It is not your normal mailbox password.', pl: 'Osobne, ograniczone hasło utworzone dla jednej aplikacji lub połączenia. To nie jest zwykłe hasło do skrzynki.' } },
  'scheduled-task': { title: { en: 'Scheduled task', pl: 'Zaplanowane zadanie' }, definition: { en: 'An instruction that an AI service runs at a chosen time or on a repeating schedule.', pl: 'Instrukcja, którą usługa AI wykonuje o wybranej porze albo cyklicznie.' } },
  'custom-gpt': { title: { en: 'Custom GPT / assistant', pl: 'Własny GPT / asystent' }, definition: { en: 'A version of an AI assistant configured for one purpose, with its own instructions, files, or preferred style.', pl: 'Wersja asystenta AI skonfigurowana do jednego celu, z własnymi instrukcjami, plikami lub stylem.' } },
  'privacy-controls': { title: { en: 'Privacy controls', pl: 'Ustawienia prywatności' }, definition: { en: 'Settings that decide how a service stores, remembers, or may use your conversations and files.', pl: 'Ustawienia określające, jak usługa przechowuje, zapamiętuje i może wykorzystywać rozmowy oraz pliki.' } },
  verification: { title: { en: 'Verification', pl: 'Weryfikacja' }, definition: { en: 'Checking an AI answer against the original document, source, calculation, or a trusted person before relying on it.', pl: 'Sprawdzenie odpowiedzi AI w dokumencie, źródle, obliczeniu lub u zaufanej osoby przed użyciem jej w praktyce.' } },
  hallucination: { title: { en: 'Hallucination', pl: 'Halucynacja modelu' }, definition: { en: 'A confident-sounding but unsupported or false AI answer, such as an invented fact, quote, date, or source.', pl: 'Brzmiąca pewnie, ale nieprawdziwa lub niepotwierdzona odpowiedź AI, np. wymyślony fakt, cytat, termin albo źródło.' } },
  bias: { title: { en: 'Bias', pl: 'Stronniczość' }, definition: { en: 'A repeated tendency to favour one group, assumption, or interpretation. Check whether important viewpoints are missing.', pl: 'Powtarzająca się tendencja do faworyzowania grupy, założenia lub interpretacji. Sprawdź, czy nie brakuje ważnej perspektywy.' } },
  tool: { title: { en: 'Tool', pl: 'Narzędzie' }, definition: { en: 'A capability an AI can use to do something concrete, such as read a file, search the web, or create a document.', pl: 'Funkcja, której AI może użyć do konkretnego działania, np. odczytania pliku, wyszukania informacji lub utworzenia dokumentu.' } },
  llm: { title: { en: 'LLM', pl: 'LLM' }, definition: { en: 'Short for large language model: the type of AI trained to work with language behind many chat assistants.', pl: 'Skrót od „duży model językowy”: rodzaj AI wytrenowany do pracy z językiem, stojący za wieloma asystentami.' } },
  agent: { title: { en: 'Agent', pl: 'Agent' }, definition: { en: 'An AI that can plan several steps and use tools to reach a goal, rather than only answer once.', pl: 'AI, która potrafi zaplanować kilka kroków i użyć narzędzi, aby osiągnąć cel, zamiast tylko raz odpowiedzieć.' } },
  subagent: { title: { en: 'Subagent', pl: 'Subagent' }, definition: { en: 'A specialist helper to which another AI delegates one focused task.', pl: 'Pomocniczy specjalista AI, któremu inna AI przekazuje jedno konkretne zadanie.' } },
  skill: { title: { en: 'Skill', pl: 'Umiejętność (skill)' }, definition: { en: 'A saved set of instructions that helps an AI follow a repeatable process for one type of task.', pl: 'Zapisany zestaw instrukcji, który pomaga AI powtarzalnie wykonywać określony rodzaj zadania.' } },
  hook: { title: { en: 'Hook', pl: 'Hook' }, definition: { en: 'A small automatic action that runs at a chosen moment, such as after a file is changed.', pl: 'Mała automatyczna akcja uruchamiana w wybranym momencie, np. po zmianie pliku.' } },
  mcp: { title: { en: 'MCP (Model Context Protocol)', pl: 'MCP (Model Context Protocol)' }, definition: { en: 'A common way to connect an AI with outside tools or data. Treat every connection like giving a key: check access and start with the smallest scope.', pl: 'Wspólny sposób łączenia AI z zewnętrznymi narzędziami lub danymi. Traktuj każde połączenie jak klucz: sprawdź dostęp i zacznij od najmniejszego zakresu.' } },
  plugin: { title: { en: 'Plugin / app extension', pl: 'Wtyczka / rozszerzenie' }, definition: { en: 'An add-on that gives an AI service extra abilities or connects it with another service. Review its permissions before installing.', pl: 'Dodatek, który daje usłudze AI nowe możliwości albo łączy ją z inną usługą. Przed instalacją sprawdź uprawnienia.' } },
  'system-prompt': { title: { en: 'System prompt', pl: 'Prompt systemowy' }, definition: { en: 'A background instruction that sets the assistant’s role and rules for a conversation.', pl: 'Ukryta instrukcja określająca rolę i zasady asystenta w rozmowie.' } },
  token: { title: { en: 'Token', pl: 'Token' }, definition: { en: 'A small piece of text used to measure how much an AI reads and writes. It can be a whole word or part of one.', pl: 'Mały fragment tekstu używany do mierzenia, ile AI czyta i zapisuje. Może być całym słowem albo jego częścią.' } },
  'context-window': { title: { en: 'Context window', pl: 'Okno kontekstu' }, definition: { en: 'The amount of conversation and files an AI can consider at one time.', pl: 'Ilość rozmowy i plików, które AI może wziąć pod uwagę jednocześnie.' } },
  'slash-command': { title: { en: 'Slash command', pl: 'Polecenie ze slashem' }, definition: { en: 'A shortcut that starts with / and launches a saved instruction or action.', pl: 'Skrót zaczynający się od /, który uruchamia zapisaną instrukcję lub akcję.' } },
  frontmatter: { title: { en: 'Frontmatter', pl: 'Frontmatter' }, definition: { en: 'A small description block at the top of a library file. It tells the site what the material is called and how to display it.', pl: 'Mały blok opisu na początku pliku biblioteki. Informuje stronę, jak nazywa się materiał i jak go wyświetlić.' } },
};

export function getGlossaryTerm(name: string): GlossaryEntry | undefined {
  return GLOSSARY[name.toLowerCase()];
}

export function allGlossaryTerms(): (GlossaryEntry & { key: string })[] {
  return Object.entries(GLOSSARY).map(([key, entry]) => ({ key, ...entry }));
}
